[variables]
npm_config_legacy_peer_deps = "true"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_22"]
cmds = ["useradd -m -s /bin/bash node || true"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "su -p node -c 'npm run start'"
